[workspace]
name = "OSM-vs-EGiB-Data-Conformance-Study"
version = "0.1.0"
authors = ["MaksHubertDabrowski <MaksDabrowski@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
python = "3.11.*"
geopandas = ">=1.0"
loguru = "*"
osmnx = ">=1.9"
pandas = ">=2.1"
pyogrio = "*"

# UWAGA: Usunęliśmy sekcję [activation]. 
# Ścieżki do ArcGIS obsłuży skrypt check_install.py

[tasks]
check-env = "python scripts/check_install.py"
compare = "python scripts/compare_logic.py"